# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-21 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_lunch', model_utils.fields.StatusField(choices=[('confirmed', 'confirmed'), ('confirmed_not', 'confirmed_not'), ('unknown', 'unknown')], db_index=True, default='unknown', max_length=100, no_check_for_status=True)),
                ('created_date', models.DateTimeField()),
                ('message', models.TextField()),
                ('report_as_not_menu', models.IntegerField(default=0)),
                ('vote_up', models.IntegerField(default=0)),
                ('vote_down', models.IntegerField(default=0)),
                ('facebook_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('facebook_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='facebookpost',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunch.Restaurant'),
        ),
    ]
