# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-05 17:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lunch', '0002_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='facebook_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='restaurants',
            field=models.ManyToManyField(to='lunch.Restaurant'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
