# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-11 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0004_admin_hotfix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats_taken', models.IntegerField(default=0)),
                ('seats_total', models.IntegerField(default=0)),
                ('date_declared', models.DateField(editable=False)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunch.Restaurant')),
            ],
        ),
    ]
