# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-11 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0005_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='voted_down_on',
            field=models.ManyToManyField(related_name='voted_down_on', to='lunch.FacebookPost'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='voted_up_on',
            field=models.ManyToManyField(related_name='voted_up_on', to='lunch.FacebookPost'),
        ),
    ]
