# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-14 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('lunch', '0006_occupation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_lunch', model_utils.fields.StatusField(choices=[('confirmed', 'confirmed'), ('confirmed_not', 'confirmed_not'), ('unknown', 'unknown')], db_index=True, default='unknown', max_length=100, no_check_for_status=True)),
                ('created_date', models.DateTimeField()),
                ('message', models.TextField()),
                ('report_as_not_menu', models.IntegerField(default=0)),
                ('vote_up', models.IntegerField(default=0)),
                ('vote_down', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuEmail',
            fields=[
                ('menubase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lunch.MenuBase')),
                ('sender_email', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('lunch.menubase',),
        ),
        migrations.CreateModel(
            name='MenuFacebook',
            fields=[
                ('menubase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lunch.MenuBase')),
                ('facebook_id', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('lunch.menubase',),
        ),
        migrations.AddField(
            model_name='menubase',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_lunch.menubase_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='menubase',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunch.Restaurant'),
        ),
    ]
