# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-14 18:27
from __future__ import unicode_literals

from django.db import migrations, models


def remove_votes(apps, schema_editor):
    UserProfile = apps.get_model("lunch", "UserProfile")

    for user_profile in UserProfile.objects.all():
        user_profile.voted_down_on.clear()
        user_profile.voted_up_on.clear()


class Migration(migrations.Migration):
    dependencies = [
        ('lunch', '0008_move_data_base_menu'),
    ]

    operations = [
        migrations.RunPython(remove_votes),
        migrations.AlterField(
            model_name='userprofile',
            name='voted_down_on',
            field=models.ManyToManyField(related_name='voted_down_on', to='lunch.MenuBase'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='voted_up_on',
            field=models.ManyToManyField(related_name='voted_up_on', to='lunch.MenuBase'),
        ),
    ]
