# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-14 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0010_remove_facebook_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menufacebook',
            old_name='facebook_id',
            new_name='post_id',
        ),
    ]
