# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-15 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0014_remove_old_foreign_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
