# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-16 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0015_delete_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='voted_down_on',
            field=models.ManyToManyField(blank=True, related_name='voted_down_on', to='lunch.MenuBase'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='voted_up_on',
            field=models.ManyToManyField(blank=True, related_name='voted_up_on', to='lunch.MenuBase'),
        ),
    ]
